name = "office"
step_limit = 100
seed = 1

layout = """
#######
#A....#
#.....#
#.....#
#.....#
#....B#
#######
"""

[[labels]]
identifier = "A"
constraint = false
random = false

[[labels]]
identifier = "B"
constraint = true
random = false
